# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-25 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_profile_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=250)),
                ('commented_project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='post.Project')),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='post.Profile')),
            ],
        ),
    ]
